"""Pure PyTorch GraphSAGE-style trainer for account fraud detection.

The original uploaded GNN file used PyTorch Geometric. This project version keeps
installation simpler by using a local PyTorch implementation of account-level
GraphSAGE over the graph CSVs generated by graph_dataset_builder.py.
"""

from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Tuple

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import average_precision_score, f1_score, precision_score, recall_score, roc_auc_score
from sklearn.preprocessing import StandardScaler

from fraud_ml.gnn.graph_dataset_builder import ACCOUNT_FEATURE_COLUMNS

logger = logging.getLogger("fraud_ml.gnn.graph_trainer")

try:  # Keep FastAPI usable even before torch is installed.
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
    HAS_TORCH = True
except Exception:  # pragma: no cover - environment dependent
    torch = None
    nn = object
    F = None
    HAS_TORCH = False
    AccountGraphSAGE = None


@dataclass
class GNNTrainConfig:
    graph_data_dir: str = "data/gnn"
    dataset_name: str = "fraud_graph"
    artifact_dir: str = "artifacts/gnn"
    model_version: str = "v1"
    device: str = "auto"
    hidden_dim: int = 64
    epochs: int = 35
    learning_rate: float = 0.003
    weight_decay: float = 0.0005
    dropout: float = 0.25
    patience: int = 6
    seed: int = 42
    include_shared_entity_edges: bool = True


if HAS_TORCH:
    class GraphSAGELayer(nn.Module):
        def __init__(self, in_dim: int, out_dim: int):
            super().__init__()
            self.self_linear = nn.Linear(in_dim, out_dim)
            self.neigh_linear = nn.Linear(in_dim, out_dim)

        def forward(self, x, edge_index):
            src, dst = edge_index
            agg = torch.zeros_like(x)
            deg = torch.zeros((x.size(0), 1), device=x.device)
            agg.index_add_(0, dst, x[src])
            deg.index_add_(0, dst, torch.ones((dst.numel(), 1), device=x.device))
            agg = agg / deg.clamp_min(1.0)
            return self.self_linear(x) + self.neigh_linear(agg)


    class AccountGraphSAGE(nn.Module):
        def __init__(self, input_dim: int, hidden_dim: int = 64, dropout: float = 0.25):
            super().__init__()
            self.layer1 = GraphSAGELayer(input_dim, hidden_dim)
            self.layer2 = GraphSAGELayer(hidden_dim, hidden_dim)
            self.classifier = nn.Sequential(
                nn.Dropout(dropout),
                nn.Linear(hidden_dim, hidden_dim // 2),
                nn.ReLU(),
                nn.Dropout(dropout),
                nn.Linear(hidden_dim // 2, 2),
            )
            self.dropout = dropout

        def forward(self, x, edge_index):
            h = F.relu(self.layer1(x, edge_index))
            h = F.dropout(h, p=self.dropout, training=self.training)
            h = F.relu(self.layer2(h, edge_index))
            return self.classifier(h)

        def embeddings(self, x, edge_index):
            h = F.relu(self.layer1(x, edge_index))
            h = F.relu(self.layer2(h, edge_index))
            return h


class GNNTrainingService:
    """Train and persist the account GraphSAGE model."""

    def __init__(self, config: GNNTrainConfig):
        if not HAS_TORCH:
            raise RuntimeError("GNN training requires PyTorch. Install all dependencies with: pip install -r requirements.txt")
        self.config = config
        self.graph_data_dir = Path(config.graph_data_dir)
        self.artifact_dir = Path(config.artifact_dir)
        self.artifact_dir.mkdir(parents=True, exist_ok=True)
        torch.manual_seed(config.seed)
        np.random.seed(config.seed)
        self.device = self._resolve_device(config.device)

    def train(self) -> Dict[str, Any]:
        run_id = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        account_df, X, y, edge_index, scaler, id_map = self._load_graph()
        train_idx, val_idx, test_idx = self._temporal_split(account_df)

        X_t = torch.tensor(X, dtype=torch.float32, device=self.device)
        y_t = torch.tensor(y, dtype=torch.long, device=self.device)
        edge_t = torch.tensor(edge_index, dtype=torch.long, device=self.device)
        train_t = torch.tensor(train_idx, dtype=torch.long, device=self.device)
        val_t = torch.tensor(val_idx, dtype=torch.long, device=self.device)
        test_t = torch.tensor(test_idx, dtype=torch.long, device=self.device)

        model = AccountGraphSAGE(input_dim=X.shape[1], hidden_dim=self.config.hidden_dim, dropout=self.config.dropout).to(self.device)
        counts = np.bincount(y[train_idx], minlength=2).astype(float)
        class_weights = counts.sum() / np.maximum(counts, 1.0)
        class_weights = class_weights / class_weights.mean()
        weight_t = torch.tensor(class_weights, dtype=torch.float32, device=self.device)
        optimizer = torch.optim.AdamW(model.parameters(), lr=self.config.learning_rate, weight_decay=self.config.weight_decay)

        best_val = -1.0
        best_state = None
        stale = 0
        history = []
        for epoch in range(1, self.config.epochs + 1):
            model.train()
            optimizer.zero_grad()
            logits = model(X_t, edge_t)
            loss = F.cross_entropy(logits[train_t], y_t[train_t], weight=weight_t)
            loss.backward()
            optimizer.step()

            with torch.no_grad():
                model.eval()
                logits = model(X_t, edge_t)
                val_probs = torch.softmax(logits[val_t], dim=1)[:, 1].detach().cpu().numpy()
                val_auc = self._safe_auc(y[val_idx], val_probs)
                val_pr = self._safe_pr_auc(y[val_idx], val_probs)
            history.append({"epoch": epoch, "loss": float(loss.detach().cpu()), "val_auc": val_auc, "val_pr_auc": val_pr})
            monitor = val_pr
            if monitor > best_val:
                best_val = monitor
                best_state = {k: v.detach().cpu().clone() for k, v in model.state_dict().items()}
                stale = 0
            else:
                stale += 1
                if stale >= self.config.patience:
                    break

        if best_state is not None:
            model.load_state_dict(best_state)

        metrics = self._evaluate(model, X_t, edge_t, y, train_idx, val_idx, test_idx)
        model_path = self.artifact_dir / f"gnn_model_{self.config.model_version}.pt"
        scaler_path = self.artifact_dir / f"gnn_scaler_{self.config.model_version}.pkl"
        id_map_path = self.artifact_dir / f"account_id_map_{self.config.model_version}.json"
        config_path = self.artifact_dir / f"gnn_config_{self.config.model_version}.json"
        metrics_path = self.artifact_dir / f"gnn_metrics_{self.config.model_version}.json"
        metadata_path = self.artifact_dir / f"training_metadata_{self.config.model_version}.json"

        torch.save(model.state_dict(), model_path)
        joblib.dump(scaler, scaler_path)
        id_map_path.write_text(json.dumps(id_map, indent=2))
        config_payload = {
            "input_dim": int(X.shape[1]),
            "hidden_dim": self.config.hidden_dim,
            "dropout": self.config.dropout,
            "feature_columns": ACCOUNT_FEATURE_COLUMNS,
        }
        config_path.write_text(json.dumps(config_payload, indent=2))
        metrics_path.write_text(json.dumps(metrics, indent=2))

        metadata = {
            "run_id": run_id,
            "created_at_utc": datetime.now(timezone.utc).isoformat(),
            "config": asdict(self.config),
            "device": str(self.device),
            "node_count": int(len(account_df)),
            "edge_count": int(edge_index.shape[1]),
            "train_rows": int(len(train_idx)),
            "val_rows": int(len(val_idx)),
            "test_rows": int(len(test_idx)),
            "metrics": metrics,
            "history": history,
            "artifacts": {
                "model_path": str(model_path),
                "scaler_path": str(scaler_path),
                "id_map_path": str(id_map_path),
                "config_path": str(config_path),
                "metrics_path": str(metrics_path),
                "metadata_path": str(metadata_path),
            },
        }
        metadata_path.write_text(json.dumps(metadata, indent=2, default=str))
        return metadata

    def _load_graph(self) -> Tuple[pd.DataFrame, np.ndarray, np.ndarray, np.ndarray, StandardScaler, Dict[str, int]]:
        account_path = self.graph_data_dir / f"{self.config.dataset_name}_account_nodes.csv"
        edge_path = self.graph_data_dir / f"{self.config.dataset_name}_edges_account_account.csv"
        shared_path = self.graph_data_dir / f"{self.config.dataset_name}_edges_account_shared_entity.csv"
        if not account_path.exists():
            raise FileNotFoundError(f"Account node CSV not found: {account_path}")
        if not edge_path.exists():
            raise FileNotFoundError(f"Account edge CSV not found: {edge_path}")
        account_df = pd.read_csv(account_path, parse_dates=["first_tx", "last_tx"])
        for col in ACCOUNT_FEATURE_COLUMNS:
            if col not in account_df.columns:
                account_df[col] = 0.0
        account_df = account_df.sort_values("node_id").reset_index(drop=True)
        id_map = {node_id: i for i, node_id in enumerate(account_df["node_id"].astype(str))}
        X_raw = account_df[ACCOUNT_FEATURE_COLUMNS].astype(float).replace([np.inf, -np.inf], np.nan).fillna(0.0).values
        scaler = StandardScaler()
        X = scaler.fit_transform(X_raw).astype(np.float32)
        y = account_df["node_label"].fillna(0).astype(int).values

        edges = pd.read_csv(edge_path)
        edge_pairs = self._edges_to_indices(edges, id_map)
        if self.config.include_shared_entity_edges and shared_path.exists():
            shared_edges = pd.read_csv(shared_path)
            edge_pairs = np.concatenate([edge_pairs, self._edges_to_indices(shared_edges, id_map)], axis=1) if edge_pairs.size else self._edges_to_indices(shared_edges, id_map)
        # Add self loops and reverse edges.
        n = len(account_df)
        self_loops = np.vstack([np.arange(n), np.arange(n)])
        if edge_pairs.size == 0:
            edge_index = self_loops
        else:
            rev = edge_pairs[::-1]
            edge_index = np.concatenate([edge_pairs, rev, self_loops], axis=1)
        return account_df, X, y, edge_index, scaler, id_map

    def _edges_to_indices(self, edges: pd.DataFrame, id_map: Dict[str, int]) -> np.ndarray:
        if edges.empty:
            return np.empty((2, 0), dtype=np.int64)
        src = edges["src_node_id"].astype(str).map(id_map)
        dst = edges["dst_node_id"].astype(str).map(id_map)
        mask = src.notna() & dst.notna()
        if mask.sum() == 0:
            return np.empty((2, 0), dtype=np.int64)
        return np.vstack([src[mask].astype(int).values, dst[mask].astype(int).values]).astype(np.int64)

    def _temporal_split(self, account_df: pd.DataFrame) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        sorted_idx = account_df.sort_values("last_tx").index.to_numpy()
        n = len(sorted_idx)
        if n < 20:
            raise ValueError("Need at least 20 account nodes for GNN train/val/test split")
        train_end = max(1, int(n * 0.80))
        val_end = max(train_end + 1, int(n * 0.90))
        return sorted_idx[:train_end], sorted_idx[train_end:val_end], sorted_idx[val_end:]

    def _evaluate(self, model, X_t, edge_t, y: np.ndarray, train_idx: np.ndarray, val_idx: np.ndarray, test_idx: np.ndarray) -> Dict[str, float]:
        with torch.no_grad():
            model.eval()
            probs = torch.softmax(model(X_t, edge_t), dim=1)[:, 1].detach().cpu().numpy()
        metrics: Dict[str, float] = {}
        for name, idx in [("train", train_idx), ("val", val_idx), ("test", test_idx)]:
            p = probs[idx]
            labels = y[idx]
            pred = (p >= 0.5).astype(int)
            metrics[f"{name}_auc"] = self._safe_auc(labels, p)
            metrics[f"{name}_pr_auc"] = self._safe_pr_auc(labels, p)
            metrics[f"{name}_f1"] = float(f1_score(labels, pred, zero_division=0))
            metrics[f"{name}_precision"] = float(precision_score(labels, pred, zero_division=0))
            metrics[f"{name}_recall"] = float(recall_score(labels, pred, zero_division=0))
            metrics[f"{name}_fraud_rate"] = float(labels.mean()) if len(labels) else 0.0
        return metrics

    def _safe_auc(self, labels: np.ndarray, probs: np.ndarray) -> float:
        return float(roc_auc_score(labels, probs)) if len(np.unique(labels)) > 1 else 0.0

    def _safe_pr_auc(self, labels: np.ndarray, probs: np.ndarray) -> float:
        return float(average_precision_score(labels, probs)) if len(np.unique(labels)) > 1 else 0.0

    def _resolve_device(self, device: str):
        if device == "auto":
            return torch.device("cuda" if torch.cuda.is_available() else "cpu")
        return torch.device(device)
